# Generated by Django 4.1 on 2025-05-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('previous_version', models.CharField(max_length=20)),
                ('current_version', models.CharField(max_length=20)),
                ('update_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'update',
            },
        ),
    ]
