# Generated by Django 4.1 on 2025-05-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsStatus',
            fields=[
                ('logistics_id', models.AutoField(primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=100)),
                ('current_location', models.CharField(db_index=True, max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('shipping_status', models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], max_length=20)),
            ],
            options={
                'db_table': 'logistics_status',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('valid_status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid')], max_length=10)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('refunded', 'Refunded')], db_index=True, max_length=10)),
                ('payment_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('quantity', models.IntegerField()),
                ('total_amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('logistics_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
