# Generated by Django 4.1 on 2025-05-19 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
        ('ordersapp', '0001_initial'),
        ('productsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productsapp.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user'),
        ),
        migrations.AddField(
            model_name='logisticsstatus',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ordersapp.order'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'product'], name='order_user_id_1fce44_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'valid_status'], name='order_user_id_fc29bc_idx'),
        ),
    ]
