# Generated by Django 4.1 on 2025-05-19 06:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AI_CustomerService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ai_customer_service',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('consultation_id', models.AutoField(primary_key=True, serialize=False)),
                ('consultation_time', models.DateTimeField(db_index=True)),
                ('user_rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('ai_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultapp.ai_customerservice')),
            ],
            options={
                'db_table': 'consultation',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('standard_answer', models.TextField()),
            ],
            options={
                'db_table': 'faq',
            },
        ),
        migrations.CreateModel(
            name='Human_CustomerService',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('online_status', models.BooleanField(db_index=True, default=False)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'db_table': 'human_customer_service',
            },
        ),
        migrations.CreateModel(
            name='ConversationRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(db_index=True)),
                ('content', models.TextField()),
                ('ai_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultapp.ai_customerservice')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultapp.consultation')),
                ('customer_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultapp.human_customerservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user')),
            ],
            options={
                'db_table': 'conversation_record',
            },
        ),
        migrations.AddField(
            model_name='consultation',
            name='customer_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultapp.human_customerservice'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user'),
        ),
        migrations.AddIndex(
            model_name='conversationrecord',
            index=models.Index(fields=['user', 'consultation'], name='conversatio_user_id_4006b7_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['user', 'customer_service'], name='consultatio_user_id_0da60f_idx'),
        ),
    ]
