# Generated by Django 4.1 on 2025-05-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='human_customerservice',
            name='password',
            field=models.CharField(default='123456', max_length=128),
        ),
        migrations.AddField(
            model_name='human_customerservice',
            name='username',
            field=models.CharField(default='cy', max_length=50, unique=True),
        ),
    ]
