# Generated by Django 4.1 on 2025-05-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultapp', '0002_human_customerservice_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationrecord',
            name='role',
            field=models.CharField(choices=[('user', '用户'), ('ai', 'AI客服'), ('human', '人工客服')], default='user', max_length=10),
        ),
    ]
